### ISSUE TITLE
Error on player leave

### ISSUE THREAD

**Issue by StrangeOne101** [StrangeOne101/ElementumAlterEgo#15]
```
[18:16:15 INFO]: Leiks lost connection: Disconnected
[18:16:15 ERROR]: Could not pass event PlayerQuitEvent to ElementumAlterEgo v1.8.6
java.util.NoSuchElementException: No value present
        at java.util.Optional.get(Optional.java:135) ~[?:1.8.0_312]
        at com.strangeone101.elementumbot.AlterEgoPlugin.relay(AlterEgoPlugin.java:222) ~[?:?]
        at com.strangeone101.elementumbot.AlterEgoListener.onLeave(AlterEgoListener.java:110) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1453.execute(Unknown Source) ~[?:?]```

**Comment by StrangeOne101** [comment]
Related
```
[18:15:28 ERROR]: Could not pass event BroadcastMessageEvent to ElementumAlterEgo v1.8.6
java.util.NoSuchElementException: No value present
        at java.util.Optional.get(Optional.java:135) ~[?:1.8.0_312]
        at com.strangeone101.elementumbot.AlterEgoPlugin.relay(AlterEgoPlugin.java:222) ~[?:?]
        at com.strangeone101.elementumbot.AlterEgoListener.onBroadcast(AlterEgoListener.java:104) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1456.execute(Unknown Source) ~[?:?]```

**Comment by StrangeOne101** [comment]
Probably actually caused from the config deleting itself, so the guild is lost
